version: '3.8'

services:
  db:
    container_name: autospace_db
    image: postgres:12.19-alpine3.20
    restart: always
    ports:
      - 2010:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data_autospace:/var/lib/postgresql/data

volumes:
  db_data_autospace:
